import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Inter as FontSans } from "next/font/google"

const inter = Inter({ subsets: ['latin'] })
import { cn } from "@/lib/utils"
import NextAuthSessionProvider from '@/providers/sessionProvider'
import { Toaster } from "@/components/ui/toaster"
 
export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import QueryProvider from '@/providers/queryProvider'




export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      
      <body className={inter.className}>
      <QueryProvider>
        <NextAuthSessionProvider>
         {children}
         <Toaster />
        </NextAuthSessionProvider>
        </QueryProvider>

      </body>
    </html>
  )
}
